### ISSUE TITLE
復帰時にタイムラインのツイートが重複する問題

### ISSUE THREAD

**Issue by cucmberium** [cucmberium/Flantter.MilkyWay#2]
[https://twitter.com/L_tan/status/747624883111104512](https://twitter.com/L_tan/status/747624883111104512)

ストリーミングと自動更新をオンにしてると起こる可能性あり

**Comment by dolciss** [comment]
ツイート拾っていただきありがとうございます、
対応が入った3.0.6にて何度かディスプレイオフから復帰させましたが
今のところ当該の現象は発生しておりませんのでご報告まで。

**Comment by cucmberium** [comment]
報告ありがとうございます。
もう少し様子を見て問題がなさそうならcloseします。

**Comment by cucmberium** [comment]
問題なさそうなのでクローズ
