### ISSUE TITLE
改行が効かないアプリがある

### ISSUE THREAD

**Issue by cucmberium** [cucmberium/Flantter.MilkyWay#67]
\r\n か \n で変わるのか？ 不明

**Comment by dolciss** [comment]
おそらく私のツイートを拾っていただけたので補足です
https://twitter.com/L_tan/status/861161247319900161
「て<改行>す<改行>と」とFlantter、公式Webからつぶやいたところ、
Flantterが「e3 81 a6 **0d** e3 81 99 **0d** e3 81 a8」となり改行されず
公式Webが「e3 81 a6 **0a** e3 81 99 **0a** e3 81 a8」となり改行されるクライアントがありました。
改行コードが「0d(\r)」ではなく「0a(\n)」でのみ改行されるようです。

ちなみに改行されないのを確認したクライアントは
Twilog(http://twilog.org/L_tan/date-170507)
![02](https://cloud.githubusercontent.com/assets/3786294/25905358/cd18cd1a-35dc-11e7-856d-6ca13be48fb9.png)
Twitcle plus(https://play.google.com/store/apps/details?id=jp.yoshika.twitcle.plus&hl=ja)
![screenshot_20170510-235105](https://cloud.githubusercontent.com/assets/3786294/25905429/f9cf9adc-35dc-11e7-8974-21fdce759653.png)
です、クライアントとしてどちらが正しい動作なのかはわかりませんが、
もしよろしければWebと同じく改行コードを\nにしていただければ…

**Comment by cucmberium** [comment]
なるほど。

確認したところWindows10のTextBoxでは改行コードが `\r\n` ではなく `\r` になっていたようです。

修正したものを次回のアップデートでストアに申請したいと思います。
情報ありがとうございます！
