### ISSUE TITLE
Cannot alt-tab or windows key-tab when Flantter is running.

### ISSUE THREAD

**Issue by Xial** [cucmberium/Flantter.MilkyWay#74]
Hello! 

Whenever Flantter is running on Windows 10 Pro with the Creator's update, if you attempt to switch to another running application by pressing Alt-Tab or Win-Tab, Flantter prevents the task switcher from rendering. 

Using alt-tab yields no overlay to show where you're tabbing.
Using win-tab causes a rapid strobing of the display, hiding the virtual desktop switcher.

I can recreate this by simply opening Flantter. Once it is closed, the same keystrokes work as expected. 
The strobing and hiding of the overlay only happens on the virtual desktop that Flantter is assigned to.

**Comment by cucmberium** [comment]
Sorry for my late reply.

I could not reproduce the bug in my environment.
Do you use any applications that add shortcut keys such as SylphyHorn or Windows 10 virtual desktop enhancer?
Because there is a possibility that IME may be the cause, please also check that symptoms appear when switching to English input for testing.

**Comment by Xial** [comment]
I use Windows 10 Pro with Creator's update in English only, and do not use an IME for input. This is on a recent, clean install of Windows 10 Pro, updated to the Creator's update.

I do not normally use the virtual desktop, but when testing for this report, I tried it to see if the cause could be isolated to just one of the virtual desktops. 
I am not using any type of enhancer for the virtual desktop, and I am not familiar with SylphyHorn. I use no other applications that add shortcut keys.

Thank you!

**Comment by Xial** [comment]
I recently uninstalled and reinstalled Flantter once more on this machine, and can no longer reproduce the issue. 
I have not made any changes to my system other than the uninstall and reinstall of Flantter, but I think it is safe to say that the issue appears to be resolved at this time.
Thank you for looking into this for me!
