### ISSUE TITLE
マストドンに投稿されたTwitterのリンクが開かない

### ISSUE THREAD

**Issue by osapon** [cucmberium/Flantter.MilkyWay#75]
タイトルの通りなのですが、twitterのアカウントを登録していない状態でステータスページへのリンクをクリックすると、ステータス詳細がスライドしてきますが、内容が表示されていない状態です。
他のURLと同じくブラウザを開いてもらって構わないと思います。

**Comment by cucmberium** [comment]
返信遅れ申し訳ありません。

本来マストドンを使用している際Twitterのリンクはブラウザで開かれるのが正しい挙動なのですが、
現在諸事情により実装できていません。
後のアップデートで修正したいと思います。
